# Generated by Django 3.0.3 on 2020-12-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_auto_20200218_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner_detail',
            old_name='rent',
            new_name='price',
        ),
        migrations.AddField(
            model_name='owner_detail',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner_detail',
            name='fuel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner_detail',
            name='kmdriven',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner_detail',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner_detail',
            name='noofowner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner_detail',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
