# Generated by Django 3.0.3 on 2020-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_auto_20201214_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_detail',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
