# Generated by Django 3.0.3 on 2020-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_owner_detail_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_detail',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
