# Generated by Django 3.2.9 on 2022-04-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_auto_20201215_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(null=True)),
                ('contact', models.IntegerField(null=True)),
                ('message1', models.TextField(null=True)),
            ],
        ),
    ]
