# Generated by Django 3.1.3 on 2022-04-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_send_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_detail',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.owner_detail'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
