# Generated by Django 3.1.3 on 2022-04-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0010_auto_20220423_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_status', to='Room.owner_detail'),
        ),
    ]
