# Generated by Django 3.1.3 on 2022-04-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Room', '0011_auto_20220423_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourate', models.BooleanField(default=False)),
                ('car_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.owner_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
